name: Magalix
author: Magalix Corporation
description: Identify violations in your IaC files using Magalix Action

inputs:
  webhook:
    description: magalix guard webhook
    required: true
  directory:
    description: root directory to scan
    default: '.'
    required: false
  token:
    default: ${{ github.token }}
  branch:
    default: ${{ github.head_ref || github.ref }}
  commit:
    default: ${{ github.event.pull_request.head.sha || github.sha }}
  gh-code-scanning:
    description: enable github code scanning
    default: true
  auto-remediation:
    description: enable auto-remediation
    default: true

branding:
  color: blue
  icon: shield

runs:
  using: docker
  image: docker://magalixcorp/iac-scanner:test
  args:
    - mglx-scanner
    - --webhook
    - ${{ inputs.webhook }}
    - --directory
    - ${{ inputs.directory }}
    - --gh-token
    - ${{ inputs.token }}
    - --branch
    - ${{ inputs.branch }}
    - --commit
    - ${{ inputs.commit }}
    - ${{ inputs.gh-code-scanning == "true" && '--gh-code-scanning' || '' }}
    - ${{ inputs.auto-remediation == "true" && '--auto-fix' || '' }}
