name: Magalix
author: Magalix Corporation
description: Identify violations in your IaC files using Magalix Action

inputs:
  webhook:
    description: magalix guard webhook
    required: true
  directory:
    description: root directory to scan
    default: '.'
    required: false
  token:
    default: ${{ github.token }}

branding:
  color: blue
  icon: shield

runs:
  using: docker
  image: docker://magalixcorp/iac-scanner:test
  args:
    - mglx-scanner
    - --webhook
    - ${{ inputs.webhook }}
    - --directory
    - ${{ inputs.directory }}
    - --gh-token
    - ${{ inputs.token }}
    - --gh-code-scanning
    - --auto-fix
